# Generated by Django 3.1.4 on 2020-12-02 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_auto_20201129_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='unlocks',
            field=models.ManyToManyField(blank=True, related_name='unlocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
