# Generated by Django 3.1.4 on 2020-12-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_unlocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
