# Generated by Django 3.1.4 on 2020-12-02 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0004_note_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='my_notes', to='users.user'),
            preserve_default=False,
        ),
    ]
