# Generated by Django 3.1.4 on 2020-12-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='note',
            name='unlocks',
        ),
    ]
