# Generated by Django 3.1.4 on 2020-12-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20201203_1919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
