# Generated by Django 3.1.4 on 2020-12-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_delete_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
